using System.Text.Json.Nodes;

namespace Edvanz.API.Filters;

/// <summary>
/// Swagger examples for the Authentication module (AuthController).
/// All examples use real seeded identities from DbInitializer — usernames and the
/// default seed password "Edvanz@2026". Numeric account ids are illustrative only:
/// they are identity-generated by service-driven seeding and are NOT stable across
/// rebuilds, so clients must never hardcode them.
/// </summary>
public sealed class AuthExampleProvider : EndpointExampleProvider
{
    public override EndpointExampleSet? GetExamples(string httpMethod, string normalizedRoute)
    {
        if (httpMethod != "POST") return null;

        return normalizedRoute switch
        {
            "api/auth/sign-up" => SignUp(),
            "api/auth/generate-otp" => GenerateOtp(),
            "api/auth/verify-otp" => VerifyOtp(),
            "api/auth/login" => Login(),
            "api/auth/admin-login" => AdminLogin(),
            "api/auth/refresh" => Refresh(),
            "api/auth/change-password" => ChangePassword(),
            "api/auth/sigup-by-google" => GoogleSignUp(),
            "api/auth/complete-profile" => CompleteProfile(),
            "api/auth/logout" => Logout(),
            _ => null
        };
    }

    // ─────────────────────────── shared builders ───────────────────────────

    /// <summary>Representative AuthResponse payload for a seeded TEACHER (teacher1 — Ahmed Mostafa).</summary>
    private static JsonObject TeacherAuthData() => new()
    {
        ["accessToken"] = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.<header>.<signature>",
        ["refreshToken"] = "a7f3c1e0-9b2d-4c8a-bf11-6e2d0c4a9d31",
        ["userAccountData"] = new JsonObject
        {
            ["accountId"] = 2,                 // illustrative — do not hardcode
            ["userName"] = "teacher1",
            ["fullName"] = "Ahmed Mostafa",
            ["accountType"] = "Teacher",
            ["models"] = new JsonArray(
                "Student", "Session", "Attendance", "Payment",
                "Event-Based Payment", "Exams And Homework", "Messaging", "Videos"),
            ["permissions"] = null,              // teachers are module-gated, not permission-gated
            ["teacherIds"] = new JsonArray(1)   // illustrative
        }
    };

    /// <summary>Representative AuthResponse payload for the seeded SUPER ADMIN.</summary>
    private static JsonObject AdminAuthData() => new()
    {
        ["accessToken"] = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.<header>.<signature>",
        ["refreshToken"] = "f0c9b8a7-1234-4def-9abc-5e6f7a8b9c0d",
        ["userAccountData"] = new JsonObject
        {
            ["accountId"] = 1,                 // illustrative
            ["userName"] = "superadmin",
            ["fullName"] = "Platform Administrator",
            ["accountType"] = "SuperAdmin",
            ["models"] = null,
            ["permissions"] = null,
            ["teacherIds"] = new JsonArray()
        }
    };

    // ─────────────────────────── per-endpoint ───────────────────────────

    private EndpointExampleSet SignUp() => new()
    {
        // sign-up is multipart/form-data ([FromForm] SigupDto incl. optional idImage),
        // so the request body is documented via the form schema + XML comments rather
        // than a JSON example. Response example only.
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope(
                "Account created. Verify your phone via OTP to activate it.", null),
            ["400"] = FailureEnvelope("This username is already in use.")
        }
    };

    private EndpointExampleSet GenerateOtp() => new()
    {
        // phoneNumber is a [FromQuery] parameter — no request body.
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope("OTP generated.", JsonValue.Create("123456")!),
            ["400"] = FailureEnvelope("No account found for this phone number.")
        }
    };

    private EndpointExampleSet VerifyOtp() => new()
    {
        RequestBody = new JsonObject
        {
            ["phoneNumber"] = "01000000001",   // teacher1 (seeded)
            ["otp"] = "123456"
        },
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope("Account verified successfully.", null),
            ["400"] = FailureEnvelope("Invalid or expired OTP.")
        }
    };

    private EndpointExampleSet Login() => new()
    {
        RequestBodyExamples = new Dictionary<string, JsonNode>
        {
            ["teacher1 — Ahmed Mostafa (all 8 modules)"] =
              new JsonObject { ["userName"] = "teacher1", ["password"] = "Edvanz@2026" },
            ["teacher2 — Mariam Hassan (Student/Session/Attendance)"] =
              new JsonObject { ["userName"] = "teacher2", ["password"] = "Edvanz@2026" },
            ["assistant1a — Sara Ibrahim (full delegate of teacher1)"] =
              new JsonObject { ["userName"] = "assistant1a", ["password"] = "Edvanz@2026" },
            ["assistant1b — Khaled Nasser (read-mostly under teacher1)"] =
              new JsonObject { ["userName"] = "assistant1b", ["password"] = "Edvanz@2026" },
            ["assistant2a — Nour Adel (under teacher2)"] =
              new JsonObject { ["userName"] = "assistant2a", ["password"] = "Edvanz@2026" },
        },
        ResponseExamples = new Dictionary<string, IReadOnlyDictionary<string, JsonNode>>
        {
            ["200"] = new Dictionary<string, JsonNode>
            {
                ["teacher1 (Teacher — all modules)"] = SuccessEnvelope(
                  "Logged in successfully.",
                  AuthData(2, "teacher1", "Ahmed Mostafa", "Teacher",
                           AllModules(), permissions: null, teacherIds: new JsonArray(1))),

                ["teacher2 (Teacher — limited modules)"] = SuccessEnvelope(
                  "Logged in successfully.",
                  AuthData(3, "teacher2", "Mariam Hassan", "Teacher",
                           new JsonArray("Student", "Session", "Attendance"),
                           permissions: null, teacherIds: new JsonArray(2))),

                // Assistant resolves to its OWNING tutor: teacherIds points at teacher1.
                // models/permissions reflect the assistant's granted profile (representative here).
                ["assistant1a (Assistant of teacher1)"] = SuccessEnvelope(
                  "Logged in successfully.",
                  AuthData(4, "assistant1a", "Sara Ibrahim", "Assistant",
                           AllModules(),
                           permissions: new JsonArray("Add", "ViewProfile"),
                           teacherIds: new JsonArray(1))),
            }
        },
        Responses = new Dictionary<string, JsonNode>
        {
            ["400"] = FailureEnvelope("Invalid username or password.")
        }
    };

    /// <summary>Fresh array of the 8 module names (teacher1's full grant). New instance per call
    /// so JsonNodes are never re-parented across examples.</summary>
    private static JsonArray AllModules() => new(
        "Student", "Session", "Attendance", "Payment",
        "Event-Based Payment", "Exams And Homework", "Messaging", "Videos");

    /// <summary>Builds an AuthResponse payload. Numeric ids/tokens are illustrative only.</summary>
    private static JsonObject AuthData(
        long accountId, string userName, string fullName, string accountType,
        JsonArray? models, JsonArray? permissions, JsonArray teacherIds) => new()
        {
            ["accessToken"] = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.<header>.<signature>",
            ["refreshToken"] = "a7f3c1e0-9b2d-4c8a-bf11-6e2d0c4a9d31",
            ["userAccountData"] = new JsonObject
            {
                ["accountId"] = accountId,
                ["userName"] = userName,
                ["fullName"] = fullName,
                ["accountType"] = accountType,
                ["models"] = models,
                ["permissions"] = permissions,
                ["teacherIds"] = teacherIds
            }
        };

    private EndpointExampleSet AdminLogin() => new()
    {
        RequestBody = new JsonObject
        {
            ["userName"] = "superadmin",
            ["password"] = "Edvanz@2026"
        },
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope("Logged in successfully.", AdminAuthData()),
            // Same generic message for wrong-password and not-an-admin (no user-type enumeration).
            ["400"] = FailureEnvelope("Invalid username or password.")
        }
    };

    private EndpointExampleSet Refresh() => new()
    {
        RequestBody = new JsonObject
        {
            ["token"] = "a7f3c1e0-9b2d-4c8a-bf11-6e2d0c4a9d31"
        },
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope("Token refreshed.", TeacherAuthData()),
            ["400"] = FailureEnvelope("Invalid, expired, or revoked refresh token.")
        }
    };

    private EndpointExampleSet ChangePassword() => new()
    {
        RequestBody = new JsonObject
        {
            ["oldPassword"] = "Edvanz@2026",
            ["newPassword"] = "NewP@ssw0rd1",
            ["confirmPassword"] = "NewP@ssw0rd1",
            ["logOutFromAllDevices"] = true
        },
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope("Password changed successfully.", null),
            ["400"] = FailureEnvelope("The current password is incorrect."),
            ["401"] = FailureEnvelope("User could not be resolved from token.")
        }
    };

    private EndpointExampleSet GoogleSignUp() => new()
    {
        RequestBody = new JsonObject
        {
            ["clientDeviceToken"] = "<google-id-token-from-client-sdk>"
        },
        Responses = new Dictionary<string, JsonNode>
        {
            // Returning user (linked + completed): full AuthResponse.
            ["200"] = SuccessEnvelope("Logged in successfully.", TeacherAuthData()),
            ["400"] = FailureEnvelope("Invalid Google token.")
        }
    };

    private EndpointExampleSet CompleteProfile() => new()
    {
        RequestBody = new JsonObject
        {
            ["userType"] = "Teacher",
            ["fullName"] = "Omar Khaled",
            ["username"] = "omar.k",
            ["phoneNumber"] = "01000000099",
            ["languagePreference"] = "en",
            ["subjectIds"] = new JsonArray(1),
            ["studentCapacity"] = 500,
            ["customSubject"] = null
        },
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope("Profile completed.", TeacherAuthData()),
            ["400"] = FailureEnvelope("This username is already in use."),
            ["401"] = FailureEnvelope("Unauthorized.")
        }
    };

    private EndpointExampleSet Logout() => new()
    {
        RequestBody = new JsonObject
        {
            ["token"] = "a7f3c1e0-9b2d-4c8a-bf11-6e2d0c4a9d31",
            ["logoutAllSessions"] = false
        },
        Responses = new Dictionary<string, JsonNode>
        {
            // Idempotent — an unknown/already-revoked token still returns success.
            ["200"] = SuccessEnvelope("Logged out.", null)
        }
    };
}