using System.Text.Json.Nodes;

namespace Edvanz.API.Filters;

/// <summary>
/// Swagger request/response examples for the TeacherStudent module (TeacherStudentController).
/// All examples use real seeded identities from DbInitializer — usernames, codes, and the
/// default seed password "Edvanz@2026". Numeric IDs (id, teacherId) are illustrative only:
/// they are identity-generated by service-driven seeding and are NOT stable across rebuilds,
/// so clients must never hardcode them.
/// </summary>
public sealed class TeacherStudentExampleProvider : EndpointExampleProvider
{
    public override EndpointExampleSet? GetExamples(string method, string route)
    {
        // ENDPOINT 1 — POST api/teacherstudent — Create student
        if (method == "POST" && route == "api/teacherstudent")
            return CreateStudent();

        // ENDPOINT 2 — GET api/teacherstudent/students/{studentid} — Get by id
        if (method == "GET" && route == "api/teacherstudent/students/{studentid}")
            return GetStudentById();

        // ENDPOINT 3 — PUT api/teacherstudent/students/{studentid} — Update
        if (method == "PUT" && route == "api/teacherstudent/students/{studentid}")
            return UpdateStudent();

        // ENDPOINT 4 — GET api/teacherstudent/students — Paginated list
        if (method == "GET" && route == "api/teacherstudent/students")
            return GetStudentList();

        // ENDPOINT 5 — GET api/teacherstudent/counts — Aggregate counts
        if (method == "GET" && route == "api/teacherstudent/counts")
            return GetStudentCounts();

        // ENDPOINT 6 — DELETE api/teacherstudent/students/{studentid} — Soft delete
        if (method == "DELETE" && route == "api/teacherstudent/students/{studentid}")
            return SoftDeleteStudent();

        // ENDPOINT 7 — POST api/teacherstudent/bulk-delete — Bulk soft delete
        if (method == "POST" && route == "api/teacherstudent/bulk-delete")
            return BulkSoftDeleteStudents();

        // ENDPOINT 8 — GET api/teacherstudent/recycle-bin — Recycle bin list
        if (method == "GET" && route == "api/teacherstudent/recycle-bin")
            return GetRecycleBin();

        // ENDPOINT 9 — POST api/teacherstudent/recycle-bin/{studentid}/restore — Restore single
        if (method == "POST" && route == "api/teacherstudent/recycle-bin/{studentid}/restore")
            return RestoreStudent();

        // ENDPOINT 10 — POST api/teacherstudent/bulk-restore — Bulk restore
        if (method == "POST" && route == "api/teacherstudent/bulk-restore")
            return BulkRestoreStudents();

        // ENDPOINT 11 — DELETE api/teacherstudent/recycle-bin/{studentid}/permanent — Permanent delete
        if (method == "DELETE" && route == "api/teacherstudent/recycle-bin/{studentid}/permanent")
            return PermanentDeleteStudent();

        // ENDPOINT 12 — POST api/teacherstudent/bulk-import — Bulk import
        if (method == "POST" && route == "api/teacherstudent/bulk-import")
            return BulkImportStudents();

        return null;
    }

    // ─────────────────────────── shared builders ───────────────────────────

    /// <summary>
    /// Fresh TeacherStudentDto for the seeded student "Youssef Tarek" (student1, STU000001).
    /// New instance per call — JsonNodes cannot be re-parented across examples.
    /// Numeric id/teacherId are illustrative only.
    /// </summary>
    private static JsonObject SeededStudentDto() => new()
    {
        ["id"] = 1,                                                    // illustrative — do not hardcode
        ["teacherId"] = 1,                                             // illustrative — do not hardcode
        ["studentName"] = "Youssef Tarek",
        ["studentCode"] = "STU000001",
        ["studentPhoneNumber"] = "01000000030",
        ["parentPhoneNumber"] = "01000000040",                         // Hany Saleh's phone (seeded parent1)
        ["barcode"] = null,
        ["sessionId"] = null,
        ["hashedToken"] = "a3f7c2e0-1b4d-4a8c-bf22-7e3d1c5a9f20",
        ["isComplete"] = false,                                        // false — sessionId is null
        ["createdAt"] = "2026-01-15T10:00:00Z"
    };

    // ─────────────────────────── per-endpoint ───────────────────────────

    private EndpointExampleSet CreateStudent() => new()
    {
        RequestBodyExamples = new Dictionary<string, JsonNode>
        {
            ["Minimal — name only (teacher1 / Ahmed Mostafa)"] = new JsonObject
            {
                ["studentName"] = "Youssef Tarek",
                ["studentPhoneNumber"] = null,
                ["parentPhoneNumber"] = null,
                ["studentCode"] = null,
                ["sessionId"] = null
            },
            ["Full — all optional fields provided"] = new JsonObject
            {
                ["studentName"] = "Ahmed Khaled",
                ["studentPhoneNumber"] = "01011111111",
                ["parentPhoneNumber"] = "01022222222",
                ["studentCode"] = "AK001",
                ["sessionId"] = 5                           // illustrative session id
            }
        },
        Responses = new Dictionary<string, JsonNode>
        {
            ["201"] = SuccessEnvelope("Student created successfully.", SeededStudentDto()),
            ["400"] = FailureEnvelope("Student name is required."),
            ["404"] = FailureEnvelope("Teacher not found.")
        }
    };

    private EndpointExampleSet GetStudentById() => new()
    {
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope("Operation completed successfully.", SeededStudentDto()),
            ["404"] = FailureEnvelope("Student not found.")
        }
    };

    private EndpointExampleSet UpdateStudent() => new()
    {
        RequestBody = new JsonObject
        {
            ["studentName"] = "Youssef Tarek",
            ["studentPhoneNumber"] = "01000000030",
            ["parentPhoneNumber"] = "01000000040",
            ["studentCode"] = "STU000001",
            ["sessionId"] = null
        },
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope("Student updated successfully.", new JsonObject
            {
                ["id"] = 1,                                            // illustrative — do not hardcode
                ["teacherId"] = 1,                                     // illustrative — do not hardcode
                ["studentName"] = "Youssef Tarek",
                ["studentCode"] = "STU000001",
                ["studentPhoneNumber"] = "01000000030",
                ["parentPhoneNumber"] = "01000000040",
                ["barcode"] = null,
                ["sessionId"] = null,
                ["hashedToken"] = "a3f7c2e0-1b4d-4a8c-bf22-7e3d1c5a9f20",
                ["isComplete"] = false,
                ["createdAt"] = "2026-01-15T10:00:00Z"
            }),
            ["400"] = FailureEnvelope("Student name is required."),
            ["404"] = FailureEnvelope("Student not found."),
            ["409"] = FailureEnvelope("The record was modified by another request. Please refresh and retry.")
        }
    };

    private EndpointExampleSet GetStudentList() => new()
    {
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope("Operation completed successfully.", new JsonObject
            {
                ["data"] = new JsonArray
                {
                    new JsonObject
                    {
                        ["id"] = 1,                                    // illustrative — do not hardcode
                        ["teacherId"] = 1,                             // illustrative — do not hardcode
                        ["studentName"] = "Youssef Tarek",
                        ["studentCode"] = "STU000001",
                        ["studentPhoneNumber"] = "01000000030",
                        ["parentPhoneNumber"] = "01000000040",
                        ["barcode"] = null,
                        ["sessionId"] = null,
                        ["hashedToken"] = "a3f7c2e0-1b4d-4a8c-bf22-7e3d1c5a9f20",
                        ["isComplete"] = false,
                        ["createdAt"] = "2026-01-15T10:00:00Z"
                    }
                },
                ["page"] = 1,
                ["pageSize"] = 20,
                ["totalCount"] = 1
            })
        }
    };

    private EndpointExampleSet GetStudentCounts() => new()
    {
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope("Operation completed successfully.", new JsonObject
            {
                ["totalActiveStudents"] = 42,
                ["filteredCount"] = 42,
                ["recycleBinCount"] = 3
            })
        }
    };

    private EndpointExampleSet SoftDeleteStudent() => new()
    {
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope("Student moved to recycle bin.", null),
            ["404"] = FailureEnvelope("Student not found.")
        }
    };

    private EndpointExampleSet BulkSoftDeleteStudents() => new()
    {
        RequestBody = new JsonObject
        {
            ["studentIds"] = new JsonArray(1, 2, 3)                    // illustrative ids
        },
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope("Students moved to recycle bin.", null),
            ["400"] = FailureEnvelope("Student IDs list must not be empty."),
            ["404"] = FailureEnvelope("One or more students not found.")
        }
    };

    private EndpointExampleSet GetRecycleBin() => new()
    {
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope("Operation completed successfully.", new JsonObject
            {
                ["data"] = new JsonArray
                {
                    new JsonObject
                    {
                        ["id"] = 1,                                    // illustrative — do not hardcode
                        ["studentName"] = "Youssef Tarek",
                        ["studentCode"] = "STU000001",
                        ["studentPhoneNumber"] = "01000000030",
                        ["parentPhoneNumber"] = "01000000040",
                        ["deletedAt"] = "2026-06-28T14:00:00Z",
                        ["daysRemaining"] = 27
                    }
                },
                ["page"] = 1,
                ["pageSize"] = 20,
                ["totalCount"] = 1
            })
        }
    };

    private EndpointExampleSet RestoreStudent() => new()
    {
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope("Student restored to active list.", null),
            ["400"] = FailureEnvelope("Student is not in the recycle bin."),
            ["404"] = FailureEnvelope("Student not found.")
        }
    };

    private EndpointExampleSet BulkRestoreStudents() => new()
    {
        RequestBody = new JsonObject
        {
            ["studentIds"] = new JsonArray(1, 2)                       // illustrative ids
        },
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope("Students restored to active list.", null),
            ["400"] = FailureEnvelope("One or more students are not in the recycle bin."),
            ["404"] = FailureEnvelope("One or more students not found.")
        }
    };

    private EndpointExampleSet PermanentDeleteStudent() => new()
    {
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope("Student permanently deleted.", null),
            ["404"] = FailureEnvelope("Student not found in recycle bin.")
        }
    };

    private EndpointExampleSet BulkImportStudents() => new()
    {
        RequestBody = new JsonObject
        {
            ["students"] = new JsonArray
            {
                new JsonObject
                {
                    ["studentName"] = "Youssef Tarek",
                    ["studentPhoneNumber"] = "01000000030",
                    ["parentPhoneNumber"] = "01000000040",
                    ["studentCode"] = "STU000001"
                },
                new JsonObject
                {
                    ["studentName"] = "Ahmed Khaled",
                    ["studentPhoneNumber"] = null,
                    ["parentPhoneNumber"] = null,
                    ["studentCode"] = null                             // auto-generated (REQ-STU-018)
                },
                new JsonObject
                {
                    ["studentName"] = "",                              // skipped — empty name (REQ-STU-018)
                    ["studentPhoneNumber"] = null,
                    ["parentPhoneNumber"] = null,
                    ["studentCode"] = null
                }
            }
        },
        Responses = new Dictionary<string, JsonNode>
        {
            ["200"] = SuccessEnvelope("Import completed.", new JsonObject
            {
                ["totalProcessed"] = 3,
                ["successCount"] = 2,
                ["failedCount"] = 1,
                ["failures"] = new JsonArray
                {
                    new JsonObject
                    {
                        ["rowNumber"] = 3,
                        ["studentName"] = "",
                        ["studentCode"] = null,
                        ["reason"] = "Student name is required."
                    }
                }
            }),
            ["400"] = FailureEnvelope("Students list must not be empty.")
        }
    };
}
