<#
.SYNOPSIS
    Permissions system changes: error-message localization, Permission.Description
    column + localized descriptions, Module/Permission display-name localization,
    and the new Payment.ConfirmDeparture permission on the departure/refund endpoint.
    Anchor-based find/replace, not a git patch - safe against CRLF checkout mismatches.

.DESCRIPTION
    Implements, against muhammadkhha-png/EDvanzz @ master_integration:

      1. Distinct localized error messages for permission-denied / role-not-allowed /
         unauthenticated (401) outcomes, reusing the existing IStringLocalizer<Messages>
         mechanism throughout (ModulePermissionFilter, SecurityStampValidationMiddleware,
         SubscriptionAuthorizationResultHandler).
      2. Permission.Description (nullable) + Fluent config (HasMaxLength 500).
      3. Localized Module/Permission display names + descriptions via new resx keys
         (Module_*, Permission_*, PermissionDescription_*), wired into PermissionService,
         ProfileService, UserPermissionService via a new PermissionLocalizationExtensions
         helper. PermissionDto gains moduleName + description fields.
      4. New Payment.ConfirmDeparture permission (restricted); PaymentController's
         departure/confirm endpoint switches from roleOnly:[Teacher,SuperAdmin] to this
         permission - Teacher/SuperAdmin still pass automatically, Assistants can now be
         granted it individually via the existing Permission/Profile endpoints.

    NOT included here (deliberately, see chat write-up):
      - The EF Core migrations themselves (schema + data-only seed/backfill). Run:
          dotnet ef migrations add AddPermissionDescriptionColumn --project Edvanz.Infrastructure --startup-project Edvanz.API
          dotnet ef migrations add SeedPermissionDescriptionsAndConfirmDeparturePermission --project Edvanz.Infrastructure --startup-project Edvanz.API
        then paste the provided Up()/Down() body into the second (empty-scaffolded) migration.
      - Bulk-granting ConfirmDeparture to existing assistants - NOT done on purpose, see
        chat write-up (violates the system's own 'no default permissions' principle).

.NOTES
    Run from the repo root (muhammadkhha-png/EDvanzz). Idempotent: if an anchor is
    already gone (i.e. already applied), that step is skipped with a warning, not a
    failure.

    VERIFICATION: every anchor/replacement pair in this script was generated by diffing
    a byte-identical clone of this exact commit and validated by round-tripping the
    edits against a second fresh clone, confirming a zero-diff result before delivery.

    Saved with a UTF-8 BOM on purpose: this file, and several files it edits, contain
    non-ASCII characters (em-dashes, Egyptian Arabic text) in comments and resx values
    this script writes verbatim. Windows PowerShell 5.1 does not reliably assume UTF-8
    for a BOM-less script or a BOM-less Get-Content read - without the BOM here, and
    -Encoding UTF8 below, those bytes get silently reinterpreted under the console's
    codepage and the script (or the files it writes) end up corrupted. If you ever
    re-save this file, keep it UTF-8 with BOM.
#>

$ErrorActionPreference = 'Stop'

function Apply-Edit {
    param(
        [string]$Path,
        [string]$Old,
        [string]$New,
        [string]$Description
    )

    if (-not (Test-Path $Path)) {
        throw "File not found: $Path"
    }

    $content = Get-Content -Path $Path -Raw -Encoding UTF8

    $count = ([regex]::Matches($content, [regex]::Escape($Old))).Count

    if ($count -eq 0) {
        Write-Warning "SKIP  [$Description]  -  anchor not found in $Path (already applied, or file has diverged - check manually)."
        return
    }
    if ($count -gt 1) {
        throw "ABORT [$Description]  -  anchor found $count times in $Path, expected exactly 1. Refusing to guess which one."
    }

    $updated = $content.Replace($Old, $New)

    # OneDrive (and sometimes an AV scanner) transiently locks files under a synced Desktop
    # path right after a write. Retry with backoff instead of failing the whole run on a
    # lock that clears itself within a second or two.
    $maxAttempts = 6
    $delayMs = 400
    for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
        try {
            Set-Content -Path $Path -Value $updated -NoNewline -Encoding UTF8
            break
        }
        catch {
            if ($attempt -eq $maxAttempts) { throw }
            Start-Sleep -Milliseconds $delayMs
            $delayMs *= 2
        }
    }

    Write-Host "OK    [$Description]"
}

function New-FileWithContent {
    param(
        [string]$Path,
        [string]$Content,
        [string]$Description
    )
    if (Test-Path $Path) {
        Write-Warning "SKIP  [$Description]  -  file already exists at $Path (already applied?)."
        return
    }
    $dir = Split-Path -Path $Path -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    $maxAttempts = 6
    $delayMs = 400
    for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
        try {
            Set-Content -Path $Path -Value $Content -NoNewline -Encoding UTF8
            break
        }
        catch {
            if ($attempt -eq $maxAttempts) { throw }
            Start-Sleep -Milliseconds $delayMs
            $delayMs *= 2
        }
    }
    Write-Host "OK    [$Description]  -  created $Path"
}

# -------------------------------------------------------------------------------------
# Edit 1 of 25  -  Permission.cs - add nullable Description property
# -------------------------------------------------------------------------------------
$path1 = Join-Path $PSScriptRoot 'Edvanz.Domain\Entities\Permission.cs'
$edit1Old = @'
        public Module module { get; set; }
        public bool IsRestricted { get; set; }
        public virtual ICollection<UsersPermission> Permissions { get; set; } = new List<UsersPermission>();
        public virtual ICollection<TemplatePermisions> Profiles { get; set; } = new List<TemplatePermisions>();

'@
$edit1New = @'
        public Module module { get; set; }
        public bool IsRestricted { get; set; }

        /// <summary>
        /// Default/fallback description of what this permission grants. Backfilled via a
        /// data-only migration for existing rows (DbInitializer does not run in Production).
        /// The API response layer prefers a localized "PermissionDescription_{Module}_{Name}"
        /// resx entry over this raw value when one exists — this column is the stable,
        /// language-agnostic fallback, not the primary source of the displayed text.
        /// </summary>
        public string? Description { get; set; }
        public virtual ICollection<UsersPermission> Permissions { get; set; } = new List<UsersPermission>();
        public virtual ICollection<TemplatePermisions> Profiles { get; set; } = new List<TemplatePermisions>();

'@
Apply-Edit -Path $path1 -Old $edit1Old -New $edit1New -Description 'Permission.cs - add nullable Description property'

# -------------------------------------------------------------------------------------
# Edit 2 of 25  -  EdvanzDbContext.cs - Fluent config for Permission.Description max length
# -------------------------------------------------------------------------------------
$path2 = Join-Path $PSScriptRoot 'Edvanz.Infrastructure\Persistence\EdvanzDbContext.cs'
$edit2Old = @'
        modelBuilder.Entity<TutorModule>()
        .HasKey(ur => new { ur.TutorId, ur.ModuleId });

        #endregion

'@
$edit2New = @'
        modelBuilder.Entity<TutorModule>()
        .HasKey(ur => new { ur.TutorId, ur.ModuleId });

        // Permission.Description — nullable, bounded free text (added for the permission-
        // catalogue description feature). No other Fluent config exists for Permission today;
        // this is the first entry for it, kept minimal to match that convention.
        modelBuilder.Entity<Permission>()
            .Property(p => p.Description)
            .HasMaxLength(500);

        #endregion

'@
Apply-Edit -Path $path2 -Old $edit2Old -New $edit2New -Description 'EdvanzDbContext.cs - Fluent config for Permission.Description max length'

# -------------------------------------------------------------------------------------
# Edit 3 of 25  -  PaymentConstants.cs - add PermissionConfirmDeparture constant
# -------------------------------------------------------------------------------------
$path3 = Join-Path $PSScriptRoot 'Edvanz.Domain\Constants\PaymentConstants.cs'
$edit3Old = @'
    public const string PermissionGenerateReports = "GenerateReports";

    // ══════════════════════════════════════════════
    // PERMISSION NAMES — EVENT-BASED PAYMENT MODULE

'@
$edit3New = @'
    public const string PermissionGenerateReports = "GenerateReports";

    /// <summary>
    /// Confirm Student Departure — allows tutor/assistant to confirm a student's course
    /// withdrawal and process the associated refund or owed-amount settlement
    /// (<c>PaymentController.ConfirmDeparture</c> / <c>PaymentService.ConfirmDepartureAsync</c>).
    /// Replaces the previous <c>roleOnly: ["Teacher","SuperAdmin"]</c> gate on that endpoint —
    /// Teachers/SuperAdmin still pass automatically (module-only / bypass), Assistants now
    /// require this specific grant since it moves money.
    /// </summary>
    public const string PermissionConfirmDeparture = "ConfirmDeparture";

    // ══════════════════════════════════════════════
    // PERMISSION NAMES — EVENT-BASED PAYMENT MODULE

'@
Apply-Edit -Path $path3 -Old $edit3Old -New $edit3New -Description 'PaymentConstants.cs - add PermissionConfirmDeparture constant'

# -------------------------------------------------------------------------------------
# Edit 4 of 25  -  PaymentController.cs - ConfirmDeparture gate: roleOnly -> ModulePermission(ConfirmDeparture)
# -------------------------------------------------------------------------------------
$path4 = Join-Path $PSScriptRoot 'Edvanz.API\Controllers\PaymentController.cs'
$edit4Old = @'
    //   REQ-PAY-073/075: Departure confirmed, optional tutor override.
    //
    // AUTH: Teacher or SuperAdmin ONLY (roleOnly gate).
    //   ConfirmedByUserId sourced from JWT — never from request body.
    //
    // ══════════════════════════════════════════════════════════════════════════
    [HttpPost("departure/confirm")]
    [ModulePermission(roles: new[] { "Teacher", "SuperAdmin" }, roleOnly: true)]
    [ProducesResponseType(typeof(Edvanz.Application.Dtos.Result<Edvanz.Application.Dtos.Payment.StudentDepartureDto>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(object), StatusCodes.Status400BadRequest)]

'@
$edit4New = @'
    //   REQ-PAY-073/075: Departure confirmed, optional tutor override.
    //
    // AUTH: Payment.ConfirmDeparture permission (module-gated, not role-only).
    //   Teacher/SuperAdmin still pass automatically — Teacher via the module-only gate,
    //   SuperAdmin via the unconditional bypass in PermissionHandler. Assistants must now
    //   hold the dedicated ConfirmDeparture permission (it moves money) rather than being
    //   excluded outright as before.
    //   ConfirmedByUserId sourced from JWT — never from request body.
    //
    // ══════════════════════════════════════════════════════════════════════════
    [HttpPost("departure/confirm")]
    [ModulePermission(PaymentConstants.ModuleName, PaymentConstants.PermissionConfirmDeparture)]
    [ProducesResponseType(typeof(Edvanz.Application.Dtos.Result<Edvanz.Application.Dtos.Payment.StudentDepartureDto>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(object), StatusCodes.Status400BadRequest)]

'@
Apply-Edit -Path $path4 -Old $edit4Old -New $edit4New -Description 'PaymentController.cs - ConfirmDeparture gate: roleOnly -> ModulePermission(ConfirmDeparture)'

# -------------------------------------------------------------------------------------
# Edit 5 of 25  -  ModulePermissionFilter.cs - roleNotAllowed uses distinct RoleNotAllowed key
# -------------------------------------------------------------------------------------
$path5 = Join-Path $PSScriptRoot 'Edvanz.API\Filters\ModulePermissionFilter.cs'
$edit5Old = @'
                    return;

                context.Result = ForbidWithMessage(_localizer["Unauthorized"].Value, "roleNotAllowed");
                return;
            }

'@
$edit5New = @'
                    return;

                context.Result = ForbidWithMessage(_localizer["RoleNotAllowed"].Value, "roleNotAllowed");
                return;
            }

'@
Apply-Edit -Path $path5 -Old $edit5Old -New $edit5New -Description 'ModulePermissionFilter.cs - roleNotAllowed uses distinct RoleNotAllowed key'

# -------------------------------------------------------------------------------------
# Edit 6 of 25  -  ModulePermissionFilter.cs - permissionDenied uses distinct PermissionDenied key
# -------------------------------------------------------------------------------------
$path6 = Join-Path $PSScriptRoot 'Edvanz.API\Filters\ModulePermissionFilter.cs'
$edit6Old = @'
            context.Result = moduleNotAssigned
                ? ForbidWithMessage(_localizer["ModuleNotAssigned"].Value, "moduleAccessDenied")
                : ForbidWithMessage(_localizer["Unauthorized"].Value, "permissionDenied");
        }


'@
$edit6New = @'
            context.Result = moduleNotAssigned
                ? ForbidWithMessage(_localizer["ModuleNotAssigned"].Value, "moduleAccessDenied")
                : ForbidWithMessage(_localizer["PermissionDenied"].Value, "permissionDenied");
        }


'@
Apply-Edit -Path $path6 -Old $edit6Old -New $edit6New -Description 'ModulePermissionFilter.cs - permissionDenied uses distinct PermissionDenied key'

# -------------------------------------------------------------------------------------
# Edit 7 of 25  -  SecurityStampValidationMiddleware.cs - add IStringLocalizer using directives
# -------------------------------------------------------------------------------------
$path7 = Join-Path $PSScriptRoot 'Edvanz.API\middlewares\SecurityStampValidationMiddleware.cs'
$edit7Old = @'
using Edvanz.Domain.Constants;
using Edvanz.Domain.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;


'@
$edit7New = @'
using Edvanz.Domain.Constants;
using Edvanz.Domain.Interfaces;
using Edvanz.Domain.Resources;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;


'@
Apply-Edit -Path $path7 -Old $edit7Old -New $edit7New -Description 'SecurityStampValidationMiddleware.cs - add IStringLocalizer using directives'

# -------------------------------------------------------------------------------------
# Edit 8 of 25  -  SecurityStampValidationMiddleware.cs - inject IStringLocalizer via constructor
# -------------------------------------------------------------------------------------
$path8 = Join-Path $PSScriptRoot 'Edvanz.API\middlewares\SecurityStampValidationMiddleware.cs'
$edit8Old = @'
    private readonly RequestDelegate _next;
    private readonly ILogger<SecurityStampValidationMiddleware> _logger;

    public SecurityStampValidationMiddleware(
        RequestDelegate next,
        ILogger<SecurityStampValidationMiddleware> logger)
    {
        _next = next;
        _logger = logger;
    }


'@
$edit8New = @'
    private readonly RequestDelegate _next;
    private readonly ILogger<SecurityStampValidationMiddleware> _logger;
    private readonly IStringLocalizer<Messages> _localizer;

    public SecurityStampValidationMiddleware(
        RequestDelegate next,
        ILogger<SecurityStampValidationMiddleware> logger,
        IStringLocalizer<Messages> localizer)
    {
        _next = next;
        _logger = logger;
        _localizer = localizer;
    }


'@
Apply-Edit -Path $path8 -Old $edit8Old -New $edit8New -Description 'SecurityStampValidationMiddleware.cs - inject IStringLocalizer via constructor'

# -------------------------------------------------------------------------------------
# Edit 9 of 25  -  SecurityStampValidationMiddleware.cs - localize RejectAsync, add stable code field
# -------------------------------------------------------------------------------------
$path9 = Join-Path $PSScriptRoot 'Edvanz.API\middlewares\SecurityStampValidationMiddleware.cs'
$edit9Old = @'

    /// <summary>
    /// Writes a 401 response with a stable message body. Kept private so the
    /// rejection shape is consistent across all four rejection paths above.
    /// The client distinguishes 401-with-this-message from a routing 401 and
    /// triggers the re-authentication flow.
    /// </summary>
    private static async Task RejectAsync(HttpContext context, string message)
    {
        context.Response.StatusCode = StatusCodes.Status401Unauthorized;
        context.Response.ContentType = "application/json";
        await context.Response.WriteAsync(
            $"{{\"success\":false,\"message\":\"{message}\"}}");
    }
}
'@
$edit9New = @'

    /// <summary>
    /// Writes a 401 response with a stable, localized body. Kept private so the
    /// rejection shape is consistent across all five rejection paths above.
    ///
    /// Envelope shape matches the rest of the API (<see cref="Edvanz.Application.Dtos.Result{T}"/> /
    /// <c>ApiBaseController.ToResponse</c>): <c>code</c> is the stable, language-independent key a
    /// client can branch on to trigger its re-authentication flow; <c>message</c> is the localized,
    /// human-readable text (per the current request's Accept-Language). Previously this endpoint sent
    /// only a raw, non-localized "TokenInvalidated" string in the message field — <c>code</c> preserves
    /// that exact stable value for any existing client-side matching, while <c>message</c> now carries
    /// an actual explanation instead of a bare key.
    /// </summary>
    private async Task RejectAsync(HttpContext context, string messageKey)
    {
        context.Response.StatusCode = StatusCodes.Status401Unauthorized;
        context.Response.ContentType = "application/json; charset=utf-8";
        var payload = System.Text.Json.JsonSerializer.Serialize(new Dictionary<string, object>
        {
            ["success"] = false,
            ["code"] = messageKey,
            ["message"] = _localizer[messageKey].Value
        });
        await context.Response.WriteAsync(payload);
    }
}
'@
Apply-Edit -Path $path9 -Old $edit9Old -New $edit9New -Description 'SecurityStampValidationMiddleware.cs - localize RejectAsync, add stable code field'

# -------------------------------------------------------------------------------------
# Edit 10 of 25  -  SubscriptionAuthorizationResultHandler.cs - update XML doc for Challenged handling
# -------------------------------------------------------------------------------------
$path10 = Join-Path $PSScriptRoot 'Edvanz.API\Authorization\SubscriptionAuthorizationResultHandler.cs'
$edit10Old = @'

/// <summary>
/// Custom <see cref="IAuthorizationMiddlewareResultHandler"/> that intercepts Forbidden results
/// caused by known, user-actionable reasons and returns a clear, localized envelope instead of
/// the framework's bare, body-less 403:
///
///   - <see cref="ActiveSubscriptionHandler.SubscriptionRequiredReason"/> → "please subscribe"
///   - <see cref="PermissionHandler.ModuleNotAssignedReason"/> → "module not assigned to your account"
///
/// All other authorization outcomes (unauthenticated 401, other Forbidden reasons, success) are
/// delegated unchanged to the framework's default handler. Envelope shape matches ApiBaseController.
/// </summary>
public sealed class SubscriptionAuthorizationResultHandler : IAuthorizationMiddlewareResultHandler

'@
$edit10New = @'

/// <summary>
/// Custom <see cref="IAuthorizationMiddlewareResultHandler"/> that intercepts two categories of
/// framework outcome that otherwise reach the client as a bare, body-less response, and returns a
/// clear, localized envelope instead:
///
///   Forbidden (403), for known, user-actionable reasons:
///     - <see cref="ActiveSubscriptionHandler.SubscriptionRequiredReason"/> → "please subscribe"
///     - <see cref="PermissionHandler.ModuleNotAssignedReason"/> → "module not assigned to your account"
///
///   Challenged (401), i.e. the request carried no valid authenticated principal at all when it hit
///   the global FallbackPolicy's RequireAuthenticatedUser() — distinct from
///   SecurityStampValidationMiddleware's 401s, which cover a token that WAS present but is stale/
///   invalid/revoked. This branch covers "no token / unparseable token" specifically.
///
/// All other authorization outcomes (other Forbidden reasons, success) are delegated unchanged to
/// the framework's default handler. Envelope shape matches ApiBaseController.
/// </summary>
public sealed class SubscriptionAuthorizationResultHandler : IAuthorizationMiddlewareResultHandler

'@
Apply-Edit -Path $path10 -Old $edit10Old -New $edit10New -Description 'SubscriptionAuthorizationResultHandler.cs - update XML doc for Challenged handling'

# -------------------------------------------------------------------------------------
# Edit 11 of 25  -  SubscriptionAuthorizationResultHandler.cs - parameterize subscription-blocked WriteEnvelopeAsync call
# -------------------------------------------------------------------------------------
$path11 = Join-Path $PSScriptRoot 'Edvanz.API\Authorization\SubscriptionAuthorizationResultHandler.cs'
$edit11Old = @'
            if (blockedForSubscription)
            {
                await WriteEnvelopeAsync(context, "SubscriptionRequired", "subscriptionRequired");
                return;
            }

'@
$edit11New = @'
            if (blockedForSubscription)
            {
                await WriteEnvelopeAsync(context, "SubscriptionRequired", "subscriptionRequired", StatusCodes.Status403Forbidden);
                return;
            }

'@
Apply-Edit -Path $path11 -Old $edit11Old -New $edit11New -Description 'SubscriptionAuthorizationResultHandler.cs - parameterize subscription-blocked WriteEnvelopeAsync call'

# -------------------------------------------------------------------------------------
# Edit 12 of 25  -  SubscriptionAuthorizationResultHandler.cs - add Challenged/anonymous 401 branch
# -------------------------------------------------------------------------------------
$path12 = Join-Path $PSScriptRoot 'Edvanz.API\Authorization\SubscriptionAuthorizationResultHandler.cs'
$edit12Old = @'
            if (blockedForMissingModule)
            {
                await WriteEnvelopeAsync(context, "ModuleNotAssigned", "moduleAccessDenied");
                return;
            }
        }


'@
$edit12New = @'
            if (blockedForMissingModule)
            {
                await WriteEnvelopeAsync(context, "ModuleNotAssigned", "moduleAccessDenied", StatusCodes.Status403Forbidden);
                return;
            }
        }

        // Unauthenticated: no principal reached us at all (missing/malformed Bearer token). A
        // present-but-invalid token is instead caught earlier and 401'd by
        // SecurityStampValidationMiddleware, which never lets an authenticated-but-stale principal
        // reach here Forbidden — so this branch is specifically the "you never logged in" case.
        if (authorizeResult.Challenged && !authenticated)
        {
            await WriteEnvelopeAsync(context, "AuthenticationRequired", "authenticationRequired", StatusCodes.Status401Unauthorized);
            return;
        }


'@
Apply-Edit -Path $path12 -Old $edit12Old -New $edit12New -Description 'SubscriptionAuthorizationResultHandler.cs - add Challenged/anonymous 401 branch'

# -------------------------------------------------------------------------------------
# Edit 13 of 25  -  SubscriptionAuthorizationResultHandler.cs - parameterize WriteEnvelopeAsync signature/body
# -------------------------------------------------------------------------------------
$path13 = Join-Path $PSScriptRoot 'Edvanz.API\Authorization\SubscriptionAuthorizationResultHandler.cs'
$edit13Old = @'

    /// <summary>
    /// Writes the standard 403 envelope for a known, user-actionable Forbidden reason:
    /// <c>{ success: false, message: &lt;localized&gt;, [flagKey]: true }</c>.
    /// </summary>
    private async Task WriteEnvelopeAsync(HttpContext context, string messageKey, string flagKey)
    {
        context.Response.StatusCode = StatusCodes.Status403Forbidden;
        context.Response.ContentType = "application/json; charset=utf-8";


'@
$edit13New = @'

    /// <summary>
    /// Writes the standard envelope for a known, user-actionable authorization outcome:
    /// <c>{ success: false, message: &lt;localized&gt;, [flagKey]: true }</c>.
    /// </summary>
    private async Task WriteEnvelopeAsync(HttpContext context, string messageKey, string flagKey, int statusCode)
    {
        context.Response.StatusCode = statusCode;
        context.Response.ContentType = "application/json; charset=utf-8";


'@
Apply-Edit -Path $path13 -Old $edit13Old -New $edit13New -Description 'SubscriptionAuthorizationResultHandler.cs - parameterize WriteEnvelopeAsync signature/body'

# -------------------------------------------------------------------------------------
# Edit 14 of 25  -  PermissionDto.cs - add moduleName and description fields
# -------------------------------------------------------------------------------------
$path14 = Join-Path $PSScriptRoot 'Edvanz.Application\Dtos\PermissionsDtos\PermissionDto.cs'
$edit14Old = @'
        public bool isRestricted { get; set; }

    }
}

'@
$edit14New = @'
        public bool isRestricted { get; set; }

        /// <summary>
        /// Localized display name of the owning module (per the request's Accept-Language),
        /// falling back to the raw <c>Module.Name</c> when no localized entry exists.
        /// New field — added so callers that only had a qualified "Module.Permission" string to
        /// parse (see <c>permissionName</c> note below) have an explicit way to get the module.
        /// </summary>
        public string? moduleName { get; set; }

        /// <summary>
        /// Localized description of what this permission grants (per the request's
        /// Accept-Language), falling back to the raw <c>Permission.Description</c> column value,
        /// and null if neither exists.
        /// </summary>
        public string? description { get; set; }

    }
}

'@
Apply-Edit -Path $path14 -Old $edit14Old -New $edit14New -Description 'PermissionDto.cs - add moduleName and description fields'

# -------------------------------------------------------------------------------------
# Edit 15 of 25  -  PermissionService.cs - add using Edvanz.Application.Extensions
# -------------------------------------------------------------------------------------
$path15 = Join-Path $PSScriptRoot 'Edvanz.Application\Services\PermissionService.cs'
$edit15Old = @'
using Edvanz.Application.Dtos.ModulesPermissions;
using Edvanz.Application.Dtos.PermissionsDtos;
using Edvanz.Application.IservicesContract;
using Edvanz.Application.ServiceContract;

'@
$edit15New = @'
using Edvanz.Application.Dtos.ModulesPermissions;
using Edvanz.Application.Dtos.PermissionsDtos;
using Edvanz.Application.Extensions;
using Edvanz.Application.IservicesContract;
using Edvanz.Application.ServiceContract;

'@
Apply-Edit -Path $path15 -Old $edit15Old -New $edit15New -Description 'PermissionService.cs - add using Edvanz.Application.Extensions'

# -------------------------------------------------------------------------------------
# Edit 16 of 25  -  PermissionService.cs - localize catalogue ModuleName
# -------------------------------------------------------------------------------------
$path16 = Join-Path $PSScriptRoot 'Edvanz.Application\Services\PermissionService.cs'
$edit16Old = @'
                .GetAsync(p => moduleIds.Contains(p.ModuleId));

            // -- 4. Group by module -------------------------------------------------
            var result = teacherModules
                .Select(m => new ModulePermissionsDto
                {
                    id = m.Id,
                    ModuleName = m.Name,
                    permissions = permissions
                        .Where(p => p.ModuleId == m.Id)

'@
$edit16New = @'
                .GetAsync(p => moduleIds.Contains(p.ModuleId));

            // -- 4. Group by module (display fields localized per Accept-Language) --
            var result = teacherModules
                .Select(m => new ModulePermissionsDto
                {
                    id = m.Id,
                    ModuleName = localizer.GetLocalizedModuleName(m.Name),
                    permissions = permissions
                        .Where(p => p.ModuleId == m.Id)

'@
Apply-Edit -Path $path16 -Old $edit16Old -New $edit16New -Description 'PermissionService.cs - localize catalogue ModuleName'

# -------------------------------------------------------------------------------------
# Edit 17 of 25  -  PermissionService.cs - localize catalogue permissionName, add moduleName/description
# -------------------------------------------------------------------------------------
$path17 = Join-Path $PSScriptRoot 'Edvanz.Application\Services\PermissionService.cs'
$edit17Old = @'
                        {
                            permissionId = p.Id,
                            permissionName = p.Name,
                            isRestricted = p.IsRestricted,
                        })
                        .ToList()

'@
$edit17New = @'
                        {
                            permissionId = p.Id,
                            permissionName = localizer.GetLocalizedPermissionName(m.Name, p.Name),
                            isRestricted = p.IsRestricted,
                            moduleName = localizer.GetLocalizedModuleName(m.Name),
                            description = localizer.GetLocalizedPermissionDescription(m.Name, p.Name, p.Description),
                        })
                        .ToList()

'@
Apply-Edit -Path $path17 -Old $edit17Old -New $edit17New -Description 'PermissionService.cs - localize catalogue permissionName, add moduleName/description'

# -------------------------------------------------------------------------------------
# Edit 18 of 25  -  ProfileService.cs - add using Edvanz.Application.Extensions
# -------------------------------------------------------------------------------------
$path18 = Join-Path $PSScriptRoot 'Edvanz.Application\Services\ProfileService.cs'
$edit18Old = @'
using Edvanz.Application.Dtos.PermissionsDtos;
using Edvanz.Application.Dtos.TemplatePermissionsDtos;
using Edvanz.Application.IservicesContract;
using Edvanz.Domain.Entities;

'@
$edit18New = @'
using Edvanz.Application.Dtos.PermissionsDtos;
using Edvanz.Application.Dtos.TemplatePermissionsDtos;
using Edvanz.Application.Extensions;
using Edvanz.Application.IservicesContract;
using Edvanz.Domain.Entities;

'@
Apply-Edit -Path $path18 -Old $edit18Old -New $edit18New -Description 'ProfileService.cs - add using Edvanz.Application.Extensions'

# -------------------------------------------------------------------------------------
# Edit 19 of 25  -  ProfileService.cs - localize permission fields in GetAllProfilesWithPermissionsPerTeacherAsync
# -------------------------------------------------------------------------------------
$path19 = Join-Path $PSScriptRoot 'Edvanz.Application\Services\ProfileService.cs'
$edit19Old = @'
                {
                    permissionId = p.permision.Id,
                    permissionName = $"{p.permision.module.Name}.{p.permision.Name}",
                    isRestricted = p.permision.IsRestricted,
                }).ToList()
            }).ToList();

'@
$edit19New = @'
                {
                    permissionId = p.permision.Id,
                    permissionName = localizer.GetLocalizedPermissionName(p.permision.module.Name, p.permision.Name),
                    isRestricted = p.permision.IsRestricted,
                    moduleName = localizer.GetLocalizedModuleName(p.permision.module.Name),
                    description = localizer.GetLocalizedPermissionDescription(
                        p.permision.module.Name, p.permision.Name, p.permision.Description),
                }).ToList()
            }).ToList();

'@
Apply-Edit -Path $path19 -Old $edit19Old -New $edit19New -Description 'ProfileService.cs - localize permission fields in GetAllProfilesWithPermissionsPerTeacherAsync'

# -------------------------------------------------------------------------------------
# Edit 20 of 25  -  ProfileService.cs - localize permission fields in GetAllProfileWithPermissionsByIdAsync
# -------------------------------------------------------------------------------------
$path20 = Join-Path $PSScriptRoot 'Edvanz.Application\Services\ProfileService.cs'
$edit20Old = @'
                {
                    permissionId = p.permision.Id,
                    permissionName = $"{p.permision.module.Name}.{p.permision.Name}",
                    isRestricted = p.permision.IsRestricted,
                }).ToList()
            };

'@
$edit20New = @'
                {
                    permissionId = p.permision.Id,
                    permissionName = localizer.GetLocalizedPermissionName(p.permision.module.Name, p.permision.Name),
                    isRestricted = p.permision.IsRestricted,
                    moduleName = localizer.GetLocalizedModuleName(p.permision.module.Name),
                    description = localizer.GetLocalizedPermissionDescription(
                        p.permision.module.Name, p.permision.Name, p.permision.Description),
                }).ToList()
            };

'@
Apply-Edit -Path $path20 -Old $edit20Old -New $edit20New -Description 'ProfileService.cs - localize permission fields in GetAllProfileWithPermissionsByIdAsync'

# -------------------------------------------------------------------------------------
# Edit 21 of 25  -  UserPermissionService.cs - add using Edvanz.Application.Extensions
# -------------------------------------------------------------------------------------
$path21 = Join-Path $PSScriptRoot 'Edvanz.Application\Services\UserPermissionService.cs'
$edit21Old = @'
using Edvanz.Application.Dtos.PermissionsDtos;
using Edvanz.Application.Dtos.UsersPermissionsDtos;
using Edvanz.Application.IservicesContract;
using Edvanz.Domain.Interfaces;

'@
$edit21New = @'
using Edvanz.Application.Dtos.PermissionsDtos;
using Edvanz.Application.Dtos.UsersPermissionsDtos;
using Edvanz.Application.Extensions;
using Edvanz.Application.IservicesContract;
using Edvanz.Domain.Interfaces;

'@
Apply-Edit -Path $path21 -Old $edit21Old -New $edit21New -Description 'UserPermissionService.cs - add using Edvanz.Application.Extensions'

# -------------------------------------------------------------------------------------
# Edit 22 of 25  -  UserPermissionService.cs - localize fields in GetUserPermissionsToView
# -------------------------------------------------------------------------------------
$path22 = Join-Path $PSScriptRoot 'Edvanz.Application\Services\UserPermissionService.cs'
$edit22Old = @'
                    {
                        id = g.Key.Id,
                        ModuleName = g.Key.Name,
                        permissions = g.Select(p => new PermissionDto
                        {
                            permissionId = p.Permission.Id,
                            permissionName = p.Permission.Name,
                            isRestricted = p.Permission.IsRestricted
                        }).ToList()
                    }).ToList()

'@
$edit22New = @'
                    {
                        id = g.Key.Id,
                        ModuleName = localizer.GetLocalizedModuleName(g.Key.Name),
                        permissions = g.Select(p => new PermissionDto
                        {
                            permissionId = p.Permission.Id,
                            permissionName = localizer.GetLocalizedPermissionName(g.Key.Name, p.Permission.Name),
                            isRestricted = p.Permission.IsRestricted,
                            moduleName = localizer.GetLocalizedModuleName(g.Key.Name),
                            description = localizer.GetLocalizedPermissionDescription(
                                g.Key.Name, p.Permission.Name, p.Permission.Description),
                        }).ToList()
                    }).ToList()

'@
Apply-Edit -Path $path22 -Old $edit22Old -New $edit22New -Description 'UserPermissionService.cs - localize fields in GetUserPermissionsToView'

# -------------------------------------------------------------------------------------
# Edit 23 of 25  -  Messages.en.resx - insert error-message keys + module/permission localization keys
# -------------------------------------------------------------------------------------
$path23 = Join-Path $PSScriptRoot 'Edvanz.Domain\Messages.en.resx'
$edit23Old = @'
</root>
'@
$edit23New = @'
  <data name="PermissionDenied" xml:space="preserve">
    <value>You don't have the permission required to perform this action.</value>
  </data>
  <data name="RoleNotAllowed" xml:space="preserve">
    <value>Your account type isn't permitted to perform this action.</value>
  </data>
  <data name="AuthenticationRequired" xml:space="preserve">
    <value>You must be logged in to perform this action.</value>
  </data>
  <data name="TokenInvalidated" xml:space="preserve">
    <value>Your session is no longer valid. Please log in again.</value>
  </data>
  <data name="Module_Student" xml:space="preserve">
    <value>Students</value>
  </data>
  <data name="Module_Session" xml:space="preserve">
    <value>Sessions</value>
  </data>
  <data name="Module_Attendance" xml:space="preserve">
    <value>Attendance</value>
  </data>
  <data name="Module_Payment" xml:space="preserve">
    <value>Payments</value>
  </data>
  <data name="Module_EventBasedPayment" xml:space="preserve">
    <value>Event Payments</value>
  </data>
  <data name="Module_ExamsAndHomework" xml:space="preserve">
    <value>Exams &amp; Homework</value>
  </data>
  <data name="Module_Messaging" xml:space="preserve">
    <value>Messaging</value>
  </data>
  <data name="Module_Videos" xml:space="preserve">
    <value>Videos</value>
  </data>
  <data name="Module_OnlineExam" xml:space="preserve">
    <value>Online Exams</value>
  </data>
  <data name="Permission_Student_ViewList" xml:space="preserve">
    <value>View Student List</value>
  </data>
  <data name="PermissionDescription_Student_ViewList" xml:space="preserve">
    <value>Allows viewing the list of enrolled students.</value>
  </data>
  <data name="Permission_Student_ViewProfile" xml:space="preserve">
    <value>View Student Profile</value>
  </data>
  <data name="PermissionDescription_Student_ViewProfile" xml:space="preserve">
    <value>Allows viewing a single student's profile details.</value>
  </data>
  <data name="Permission_Student_Add" xml:space="preserve">
    <value>Add Student</value>
  </data>
  <data name="PermissionDescription_Student_Add" xml:space="preserve">
    <value>Allows adding a new student to the roster.</value>
  </data>
  <data name="Permission_Student_Edit" xml:space="preserve">
    <value>Edit Student</value>
  </data>
  <data name="PermissionDescription_Student_Edit" xml:space="preserve">
    <value>Allows editing an existing student's details.</value>
  </data>
  <data name="Permission_Student_Delete" xml:space="preserve">
    <value>Delete Student</value>
  </data>
  <data name="PermissionDescription_Student_Delete" xml:space="preserve">
    <value>Allows removing a student from the roster.</value>
  </data>
  <data name="Permission_Student_Import" xml:space="preserve">
    <value>Import Students</value>
  </data>
  <data name="PermissionDescription_Student_Import" xml:space="preserve">
    <value>Allows bulk-importing students from a file.</value>
  </data>
  <data name="Permission_Student_ExportReports" xml:space="preserve">
    <value>Export Student Reports</value>
  </data>
  <data name="PermissionDescription_Student_ExportReports" xml:space="preserve">
    <value>Allows exporting student data and reports.</value>
  </data>
  <data name="Permission_Student_ViewBarcodes" xml:space="preserve">
    <value>View Student Barcodes</value>
  </data>
  <data name="PermissionDescription_Student_ViewBarcodes" xml:space="preserve">
    <value>Allows viewing and printing student ID barcodes.</value>
  </data>
  <data name="Permission_Session_View" xml:space="preserve">
    <value>View Sessions</value>
  </data>
  <data name="PermissionDescription_Session_View" xml:space="preserve">
    <value>Allows viewing the session schedule.</value>
  </data>
  <data name="Permission_Session_Create" xml:space="preserve">
    <value>Create Session</value>
  </data>
  <data name="PermissionDescription_Session_Create" xml:space="preserve">
    <value>Allows creating a new session.</value>
  </data>
  <data name="Permission_Session_Edit" xml:space="preserve">
    <value>Edit Session</value>
  </data>
  <data name="PermissionDescription_Session_Edit" xml:space="preserve">
    <value>Allows editing an existing session's details.</value>
  </data>
  <data name="Permission_Session_Delete" xml:space="preserve">
    <value>Delete Session</value>
  </data>
  <data name="PermissionDescription_Session_Delete" xml:space="preserve">
    <value>Allows deleting a session.</value>
  </data>
  <data name="Permission_Session_ViewGroups" xml:space="preserve">
    <value>View Session Groups</value>
  </data>
  <data name="PermissionDescription_Session_ViewGroups" xml:space="preserve">
    <value>Allows viewing session groups.</value>
  </data>
  <data name="Permission_Session_AssignStudents" xml:space="preserve">
    <value>Assign Students to Session</value>
  </data>
  <data name="PermissionDescription_Session_AssignStudents" xml:space="preserve">
    <value>Allows assigning students to a session.</value>
  </data>
  <data name="Permission_Session_ManageGroups" xml:space="preserve">
    <value>Manage Session Groups</value>
  </data>
  <data name="PermissionDescription_Session_ManageGroups" xml:space="preserve">
    <value>Allows creating and managing session groups.</value>
  </data>
  <data name="Permission_Session_ViewMembership" xml:space="preserve">
    <value>View Session Membership</value>
  </data>
  <data name="PermissionDescription_Session_ViewMembership" xml:space="preserve">
    <value>Allows viewing which students belong to a session.</value>
  </data>
  <data name="Permission_Session_ManageMembership" xml:space="preserve">
    <value>Manage Session Membership</value>
  </data>
  <data name="PermissionDescription_Session_ManageMembership" xml:space="preserve">
    <value>Allows adding or removing students from a session.</value>
  </data>
  <data name="Permission_Attendance_Take" xml:space="preserve">
    <value>Take Attendance</value>
  </data>
  <data name="PermissionDescription_Attendance_Take" xml:space="preserve">
    <value>Allows recording student attendance for a session.</value>
  </data>
  <data name="Permission_Attendance_Edit" xml:space="preserve">
    <value>Edit Attendance</value>
  </data>
  <data name="PermissionDescription_Attendance_Edit" xml:space="preserve">
    <value>Allows editing a previously recorded attendance entry.</value>
  </data>
  <data name="Permission_Attendance_ViewHistory" xml:space="preserve">
    <value>View Attendance History</value>
  </data>
  <data name="PermissionDescription_Attendance_ViewHistory" xml:space="preserve">
    <value>Allows viewing past attendance records.</value>
  </data>
  <data name="Permission_Attendance_ViewAbsenceOverview" xml:space="preserve">
    <value>View Absence Overview</value>
  </data>
  <data name="PermissionDescription_Attendance_ViewAbsenceOverview" xml:space="preserve">
    <value>Allows viewing the absence overview across students.</value>
  </data>
  <data name="Permission_Attendance_GenerateReports" xml:space="preserve">
    <value>Generate Attendance Reports</value>
  </data>
  <data name="PermissionDescription_Attendance_GenerateReports" xml:space="preserve">
    <value>Allows generating and exporting attendance reports.</value>
  </data>
  <data name="Permission_Payment_Collect" xml:space="preserve">
    <value>Collect Payment</value>
  </data>
  <data name="PermissionDescription_Payment_Collect" xml:space="preserve">
    <value>Allows collecting a payment from a student.</value>
  </data>
  <data name="Permission_Payment_ViewHistory" xml:space="preserve">
    <value>View Payment History</value>
  </data>
  <data name="PermissionDescription_Payment_ViewHistory" xml:space="preserve">
    <value>Allows viewing a student's payment history.</value>
  </data>
  <data name="Permission_Payment_EditHistory" xml:space="preserve">
    <value>Edit Payment History</value>
  </data>
  <data name="PermissionDescription_Payment_EditHistory" xml:space="preserve">
    <value>Allows editing or deleting a previously recorded payment. Restricted — carries financial risk.</value>
  </data>
  <data name="Permission_Payment_ViewUnpaidStudents" xml:space="preserve">
    <value>View Unpaid Students</value>
  </data>
  <data name="PermissionDescription_Payment_ViewUnpaidStudents" xml:space="preserve">
    <value>Allows viewing the list of students with unpaid balances.</value>
  </data>
  <data name="Permission_Payment_ViewCollectorSummary" xml:space="preserve">
    <value>View Collector Summary</value>
  </data>
  <data name="PermissionDescription_Payment_ViewCollectorSummary" xml:space="preserve">
    <value>Allows viewing a summary of amounts collected by collector.</value>
  </data>
  <data name="Permission_Payment_GenerateReports" xml:space="preserve">
    <value>Generate Payment Reports</value>
  </data>
  <data name="PermissionDescription_Payment_GenerateReports" xml:space="preserve">
    <value>Allows generating and exporting payment reports.</value>
  </data>
  <data name="Permission_EventBasedPayment_View" xml:space="preserve">
    <value>View Events</value>
  </data>
  <data name="PermissionDescription_EventBasedPayment_View" xml:space="preserve">
    <value>Allows viewing payment events.</value>
  </data>
  <data name="Permission_EventBasedPayment_Create" xml:space="preserve">
    <value>Create Event</value>
  </data>
  <data name="PermissionDescription_EventBasedPayment_Create" xml:space="preserve">
    <value>Allows creating a new payment event.</value>
  </data>
  <data name="Permission_EventBasedPayment_Edit" xml:space="preserve">
    <value>Edit Event</value>
  </data>
  <data name="PermissionDescription_EventBasedPayment_Edit" xml:space="preserve">
    <value>Allows editing an existing payment event.</value>
  </data>
  <data name="Permission_EventBasedPayment_Delete" xml:space="preserve">
    <value>Delete Event</value>
  </data>
  <data name="PermissionDescription_EventBasedPayment_Delete" xml:space="preserve">
    <value>Allows deleting a payment event.</value>
  </data>
  <data name="Permission_EventBasedPayment_CollectPayment" xml:space="preserve">
    <value>Collect Event Payment</value>
  </data>
  <data name="PermissionDescription_EventBasedPayment_CollectPayment" xml:space="preserve">
    <value>Allows collecting payment for an event.</value>
  </data>
  <data name="Permission_EventBasedPayment_GenerateReports" xml:space="preserve">
    <value>Generate Event Reports</value>
  </data>
  <data name="PermissionDescription_EventBasedPayment_GenerateReports" xml:space="preserve">
    <value>Allows generating and exporting event payment reports.</value>
  </data>
  <data name="Permission_ExamsAndHomework_View" xml:space="preserve">
    <value>View Assignments</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_View" xml:space="preserve">
    <value>Allows viewing exam and homework assignments.</value>
  </data>
  <data name="Permission_ExamsAndHomework_Create" xml:space="preserve">
    <value>Create Assignment</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_Create" xml:space="preserve">
    <value>Allows creating a new exam or homework assignment.</value>
  </data>
  <data name="Permission_ExamsAndHomework_Edit" xml:space="preserve">
    <value>Edit Assignment</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_Edit" xml:space="preserve">
    <value>Allows editing an existing assignment.</value>
  </data>
  <data name="Permission_ExamsAndHomework_Delete" xml:space="preserve">
    <value>Delete Assignment</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_Delete" xml:space="preserve">
    <value>Allows deleting an assignment.</value>
  </data>
  <data name="Permission_ExamsAndHomework_RecordExamAttendanceAndGrades" xml:space="preserve">
    <value>Record Exam Attendance &amp; Grades</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_RecordExamAttendanceAndGrades" xml:space="preserve">
    <value>Allows recording exam attendance and grades.</value>
  </data>
  <data name="Permission_ExamsAndHomework_RecordHomeworkCompletion" xml:space="preserve">
    <value>Record Homework Completion</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_RecordHomeworkCompletion" xml:space="preserve">
    <value>Allows recording whether a student completed their homework.</value>
  </data>
  <data name="Permission_ExamsAndHomework_EnterPendingGrades" xml:space="preserve">
    <value>Enter Pending Grades</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_EnterPendingGrades" xml:space="preserve">
    <value>Allows entering grades that were left pending.</value>
  </data>
  <data name="Permission_ExamsAndHomework_GenerateReports" xml:space="preserve">
    <value>Generate Assignment Reports</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_GenerateReports" xml:space="preserve">
    <value>Allows generating and exporting exam/homework reports.</value>
  </data>
  <data name="Permission_ExamsAndHomework_ManageAssignments" xml:space="preserve">
    <value>Manage Assignments</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_ManageAssignments" xml:space="preserve">
    <value>Allows full management of exam/homework assignment templates and their configuration.</value>
  </data>
  <data name="Permission_Messaging_ViewHistory" xml:space="preserve">
    <value>View Message History</value>
  </data>
  <data name="PermissionDescription_Messaging_ViewHistory" xml:space="preserve">
    <value>Allows viewing sent message history.</value>
  </data>
  <data name="Permission_Messaging_SendManual" xml:space="preserve">
    <value>Send Manual Message</value>
  </data>
  <data name="PermissionDescription_Messaging_SendManual" xml:space="preserve">
    <value>Allows manually sending a message to students or parents.</value>
  </data>
  <data name="Permission_Messaging_ManageTemplates" xml:space="preserve">
    <value>Manage Message Templates</value>
  </data>
  <data name="PermissionDescription_Messaging_ManageTemplates" xml:space="preserve">
    <value>Allows creating and editing message templates.</value>
  </data>
  <data name="Permission_Messaging_ConfigureAutomatedTriggers" xml:space="preserve">
    <value>Configure Automated Triggers</value>
  </data>
  <data name="PermissionDescription_Messaging_ConfigureAutomatedTriggers" xml:space="preserve">
    <value>Allows configuring automated message triggers.</value>
  </data>
  <data name="Permission_Videos_View" xml:space="preserve">
    <value>View Videos</value>
  </data>
  <data name="PermissionDescription_Videos_View" xml:space="preserve">
    <value>Allows viewing uploaded videos.</value>
  </data>
  <data name="Permission_Videos_ManageVideos" xml:space="preserve">
    <value>Manage Videos</value>
  </data>
  <data name="PermissionDescription_Videos_ManageVideos" xml:space="preserve">
    <value>Allows uploading, editing, and deleting videos.</value>
  </data>
  <data name="Permission_OnlineExam_View" xml:space="preserve">
    <value>View Online Exams</value>
  </data>
  <data name="PermissionDescription_OnlineExam_View" xml:space="preserve">
    <value>Allows viewing online exams.</value>
  </data>
  <data name="Permission_OnlineExam_ManageExams" xml:space="preserve">
    <value>Manage Online Exams</value>
  </data>
  <data name="PermissionDescription_OnlineExam_ManageExams" xml:space="preserve">
    <value>Allows creating, editing, and managing online exams.</value>
  </data>
  <data name="Permission_Payment_ConfirmDeparture" xml:space="preserve">
    <value>Confirm Student Departure &amp; Refund</value>
  </data>
  <data name="PermissionDescription_Payment_ConfirmDeparture" xml:space="preserve">
    <value>Allows confirming a student's course withdrawal and processing the associated refund or owed-amount settlement.</value>
  </data>
</root>
'@
Apply-Edit -Path $path23 -Old $edit23Old -New $edit23New -Description 'Messages.en.resx - insert error-message keys + module/permission localization keys'

# -------------------------------------------------------------------------------------
# Edit 24 of 25  -  Messages.ar.resx - insert error-message keys + module/permission localization keys
# -------------------------------------------------------------------------------------
$path24 = Join-Path $PSScriptRoot 'Edvanz.Domain\Messages.ar.resx'
$edit24Old = @'
</root>
'@
$edit24New = @'
  <data name="PermissionDenied" xml:space="preserve">
    <value>معندكش الصلاحية اللازمة عشان تعمل العملية دي</value>
  </data>
  <data name="RoleNotAllowed" xml:space="preserve">
    <value>نوع حسابك مش مسموح له يعمل العملية دي</value>
  </data>
  <data name="AuthenticationRequired" xml:space="preserve">
    <value>لازم تسجل دخول الأول عشان تعمل العملية دي</value>
  </data>
  <data name="TokenInvalidated" xml:space="preserve">
    <value>جلستك خلصت. سجّل دخول تاني.</value>
  </data>
  <data name="Module_Student" xml:space="preserve">
    <value>الطلاب</value>
  </data>
  <data name="Module_Session" xml:space="preserve">
    <value>الحصص</value>
  </data>
  <data name="Module_Attendance" xml:space="preserve">
    <value>الحضور والغياب</value>
  </data>
  <data name="Module_Payment" xml:space="preserve">
    <value>المدفوعات</value>
  </data>
  <data name="Module_EventBasedPayment" xml:space="preserve">
    <value>مدفوعات الفعاليات</value>
  </data>
  <data name="Module_ExamsAndHomework" xml:space="preserve">
    <value>الامتحانات والواجبات</value>
  </data>
  <data name="Module_Messaging" xml:space="preserve">
    <value>الرسائل</value>
  </data>
  <data name="Module_Videos" xml:space="preserve">
    <value>الفيديوهات</value>
  </data>
  <data name="Module_OnlineExam" xml:space="preserve">
    <value>الامتحانات الأونلاين</value>
  </data>
  <data name="Permission_Student_ViewList" xml:space="preserve">
    <value>عرض قائمة الطلاب</value>
  </data>
  <data name="PermissionDescription_Student_ViewList" xml:space="preserve">
    <value>بيسمح بعرض قائمة الطلاب المسجلين.</value>
  </data>
  <data name="Permission_Student_ViewProfile" xml:space="preserve">
    <value>عرض ملف الطالب</value>
  </data>
  <data name="PermissionDescription_Student_ViewProfile" xml:space="preserve">
    <value>بيسمح بعرض تفاصيل ملف طالب معين.</value>
  </data>
  <data name="Permission_Student_Add" xml:space="preserve">
    <value>إضافة طالب</value>
  </data>
  <data name="PermissionDescription_Student_Add" xml:space="preserve">
    <value>بيسمح بإضافة طالب جديد للقائمة.</value>
  </data>
  <data name="Permission_Student_Edit" xml:space="preserve">
    <value>تعديل بيانات الطالب</value>
  </data>
  <data name="PermissionDescription_Student_Edit" xml:space="preserve">
    <value>بيسمح بتعديل بيانات طالب موجود.</value>
  </data>
  <data name="Permission_Student_Delete" xml:space="preserve">
    <value>حذف طالب</value>
  </data>
  <data name="PermissionDescription_Student_Delete" xml:space="preserve">
    <value>بيسمح بحذف طالب من القائمة.</value>
  </data>
  <data name="Permission_Student_Import" xml:space="preserve">
    <value>استيراد طلاب</value>
  </data>
  <data name="PermissionDescription_Student_Import" xml:space="preserve">
    <value>بيسمح باستيراد مجموعة طلاب دفعة واحدة من ملف.</value>
  </data>
  <data name="Permission_Student_ExportReports" xml:space="preserve">
    <value>تصدير تقارير الطلاب</value>
  </data>
  <data name="PermissionDescription_Student_ExportReports" xml:space="preserve">
    <value>بيسمح بتصدير بيانات وتقارير الطلاب.</value>
  </data>
  <data name="Permission_Student_ViewBarcodes" xml:space="preserve">
    <value>عرض باركود الطلاب</value>
  </data>
  <data name="PermissionDescription_Student_ViewBarcodes" xml:space="preserve">
    <value>بيسمح بعرض وطباعة أكواد الباركود الخاصة بالطلاب.</value>
  </data>
  <data name="Permission_Session_View" xml:space="preserve">
    <value>عرض الحصص</value>
  </data>
  <data name="PermissionDescription_Session_View" xml:space="preserve">
    <value>بيسمح بعرض جدول الحصص.</value>
  </data>
  <data name="Permission_Session_Create" xml:space="preserve">
    <value>إنشاء حصة</value>
  </data>
  <data name="PermissionDescription_Session_Create" xml:space="preserve">
    <value>بيسمح بإنشاء حصة جديدة.</value>
  </data>
  <data name="Permission_Session_Edit" xml:space="preserve">
    <value>تعديل الحصة</value>
  </data>
  <data name="PermissionDescription_Session_Edit" xml:space="preserve">
    <value>بيسمح بتعديل بيانات حصة موجودة.</value>
  </data>
  <data name="Permission_Session_Delete" xml:space="preserve">
    <value>حذف حصة</value>
  </data>
  <data name="PermissionDescription_Session_Delete" xml:space="preserve">
    <value>بيسمح بحذف حصة.</value>
  </data>
  <data name="Permission_Session_ViewGroups" xml:space="preserve">
    <value>عرض مجموعات الحصص</value>
  </data>
  <data name="PermissionDescription_Session_ViewGroups" xml:space="preserve">
    <value>بيسمح بعرض مجموعات الحصص.</value>
  </data>
  <data name="Permission_Session_AssignStudents" xml:space="preserve">
    <value>تعيين طلاب للحصة</value>
  </data>
  <data name="PermissionDescription_Session_AssignStudents" xml:space="preserve">
    <value>بيسمح بتعيين طلاب على حصة معينة.</value>
  </data>
  <data name="Permission_Session_ManageGroups" xml:space="preserve">
    <value>إدارة مجموعات الحصص</value>
  </data>
  <data name="PermissionDescription_Session_ManageGroups" xml:space="preserve">
    <value>بيسمح بإنشاء وإدارة مجموعات الحصص.</value>
  </data>
  <data name="Permission_Session_ViewMembership" xml:space="preserve">
    <value>عرض أعضاء الحصة</value>
  </data>
  <data name="PermissionDescription_Session_ViewMembership" xml:space="preserve">
    <value>بيسمح بعرض الطلاب المسجلين في حصة معينة.</value>
  </data>
  <data name="Permission_Session_ManageMembership" xml:space="preserve">
    <value>إدارة أعضاء الحصة</value>
  </data>
  <data name="PermissionDescription_Session_ManageMembership" xml:space="preserve">
    <value>بيسمح بإضافة أو إزالة طلاب من حصة معينة.</value>
  </data>
  <data name="Permission_Attendance_Take" xml:space="preserve">
    <value>تسجيل الحضور</value>
  </data>
  <data name="PermissionDescription_Attendance_Take" xml:space="preserve">
    <value>بيسمح بتسجيل حضور الطلاب في الحصة.</value>
  </data>
  <data name="Permission_Attendance_Edit" xml:space="preserve">
    <value>تعديل الحضور</value>
  </data>
  <data name="PermissionDescription_Attendance_Edit" xml:space="preserve">
    <value>بيسمح بتعديل تسجيل حضور تم إدخاله من قبل.</value>
  </data>
  <data name="Permission_Attendance_ViewHistory" xml:space="preserve">
    <value>عرض سجل الحضور</value>
  </data>
  <data name="PermissionDescription_Attendance_ViewHistory" xml:space="preserve">
    <value>بيسمح بعرض سجل الحضور السابق.</value>
  </data>
  <data name="Permission_Attendance_ViewAbsenceOverview" xml:space="preserve">
    <value>عرض نظرة عامة على الغياب</value>
  </data>
  <data name="PermissionDescription_Attendance_ViewAbsenceOverview" xml:space="preserve">
    <value>بيسمح بعرض نظرة عامة على غياب الطلاب.</value>
  </data>
  <data name="Permission_Attendance_GenerateReports" xml:space="preserve">
    <value>إصدار تقارير الحضور</value>
  </data>
  <data name="PermissionDescription_Attendance_GenerateReports" xml:space="preserve">
    <value>بيسمح بإصدار وتصدير تقارير الحضور.</value>
  </data>
  <data name="Permission_Payment_Collect" xml:space="preserve">
    <value>تحصيل المدفوعات</value>
  </data>
  <data name="PermissionDescription_Payment_Collect" xml:space="preserve">
    <value>بيسمح بتحصيل دفعة من الطالب.</value>
  </data>
  <data name="Permission_Payment_ViewHistory" xml:space="preserve">
    <value>عرض سجل المدفوعات</value>
  </data>
  <data name="PermissionDescription_Payment_ViewHistory" xml:space="preserve">
    <value>بيسمح بعرض سجل مدفوعات الطالب.</value>
  </data>
  <data name="Permission_Payment_EditHistory" xml:space="preserve">
    <value>تعديل سجل المدفوعات</value>
  </data>
  <data name="PermissionDescription_Payment_EditHistory" xml:space="preserve">
    <value>بيسمح بتعديل أو حذف دفعة مسجلة من قبل. صلاحية مقيّدة لأنها بتمس البيانات المالية.</value>
  </data>
  <data name="Permission_Payment_ViewUnpaidStudents" xml:space="preserve">
    <value>عرض الطلاب غير المسددين</value>
  </data>
  <data name="PermissionDescription_Payment_ViewUnpaidStudents" xml:space="preserve">
    <value>بيسمح بعرض قائمة الطلاب اللي عندهم مبالغ غير مسددة.</value>
  </data>
  <data name="Permission_Payment_ViewCollectorSummary" xml:space="preserve">
    <value>عرض ملخص التحصيل</value>
  </data>
  <data name="PermissionDescription_Payment_ViewCollectorSummary" xml:space="preserve">
    <value>بيسمح بعرض ملخص المبالغ المحصّلة لكل محصّل.</value>
  </data>
  <data name="Permission_Payment_GenerateReports" xml:space="preserve">
    <value>إصدار تقارير المدفوعات</value>
  </data>
  <data name="PermissionDescription_Payment_GenerateReports" xml:space="preserve">
    <value>بيسمح بإصدار وتصدير تقارير المدفوعات.</value>
  </data>
  <data name="Permission_EventBasedPayment_View" xml:space="preserve">
    <value>عرض الفعاليات</value>
  </data>
  <data name="PermissionDescription_EventBasedPayment_View" xml:space="preserve">
    <value>بيسمح بعرض فعاليات الدفع.</value>
  </data>
  <data name="Permission_EventBasedPayment_Create" xml:space="preserve">
    <value>إنشاء فعالية</value>
  </data>
  <data name="PermissionDescription_EventBasedPayment_Create" xml:space="preserve">
    <value>بيسمح بإنشاء فعالية دفع جديدة.</value>
  </data>
  <data name="Permission_EventBasedPayment_Edit" xml:space="preserve">
    <value>تعديل الفعالية</value>
  </data>
  <data name="PermissionDescription_EventBasedPayment_Edit" xml:space="preserve">
    <value>بيسمح بتعديل فعالية دفع موجودة.</value>
  </data>
  <data name="Permission_EventBasedPayment_Delete" xml:space="preserve">
    <value>حذف الفعالية</value>
  </data>
  <data name="PermissionDescription_EventBasedPayment_Delete" xml:space="preserve">
    <value>بيسمح بحذف فعالية دفع.</value>
  </data>
  <data name="Permission_EventBasedPayment_CollectPayment" xml:space="preserve">
    <value>تحصيل دفعة الفعالية</value>
  </data>
  <data name="PermissionDescription_EventBasedPayment_CollectPayment" xml:space="preserve">
    <value>بيسمح بتحصيل دفعة خاصة بفعالية معينة.</value>
  </data>
  <data name="Permission_EventBasedPayment_GenerateReports" xml:space="preserve">
    <value>إصدار تقارير الفعاليات</value>
  </data>
  <data name="PermissionDescription_EventBasedPayment_GenerateReports" xml:space="preserve">
    <value>بيسمح بإصدار وتصدير تقارير مدفوعات الفعاليات.</value>
  </data>
  <data name="Permission_ExamsAndHomework_View" xml:space="preserve">
    <value>عرض الواجبات والامتحانات</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_View" xml:space="preserve">
    <value>بيسمح بعرض الامتحانات والواجبات.</value>
  </data>
  <data name="Permission_ExamsAndHomework_Create" xml:space="preserve">
    <value>إنشاء واجب أو امتحان</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_Create" xml:space="preserve">
    <value>بيسمح بإنشاء امتحان أو واجب جديد.</value>
  </data>
  <data name="Permission_ExamsAndHomework_Edit" xml:space="preserve">
    <value>تعديل الواجب أو الامتحان</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_Edit" xml:space="preserve">
    <value>بيسمح بتعديل امتحان أو واجب موجود.</value>
  </data>
  <data name="Permission_ExamsAndHomework_Delete" xml:space="preserve">
    <value>حذف الواجب أو الامتحان</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_Delete" xml:space="preserve">
    <value>بيسمح بحذف امتحان أو واجب.</value>
  </data>
  <data name="Permission_ExamsAndHomework_RecordExamAttendanceAndGrades" xml:space="preserve">
    <value>تسجيل حضور ودرجات الامتحان</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_RecordExamAttendanceAndGrades" xml:space="preserve">
    <value>بيسمح بتسجيل حضور الامتحان ودرجاته.</value>
  </data>
  <data name="Permission_ExamsAndHomework_RecordHomeworkCompletion" xml:space="preserve">
    <value>تسجيل إنجاز الواجب</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_RecordHomeworkCompletion" xml:space="preserve">
    <value>بيسمح بتسجيل إنجاز الطالب للواجب.</value>
  </data>
  <data name="Permission_ExamsAndHomework_EnterPendingGrades" xml:space="preserve">
    <value>إدخال الدرجات المعلّقة</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_EnterPendingGrades" xml:space="preserve">
    <value>بيسمح بإدخال الدرجات اللي لسه معلّقة.</value>
  </data>
  <data name="Permission_ExamsAndHomework_GenerateReports" xml:space="preserve">
    <value>إصدار تقارير الواجبات والامتحانات</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_GenerateReports" xml:space="preserve">
    <value>بيسمح بإصدار وتصدير تقارير الامتحانات والواجبات.</value>
  </data>
  <data name="Permission_ExamsAndHomework_ManageAssignments" xml:space="preserve">
    <value>إدارة الواجبات والامتحانات</value>
  </data>
  <data name="PermissionDescription_ExamsAndHomework_ManageAssignments" xml:space="preserve">
    <value>بيسمح بالإدارة الكاملة لإعدادات الامتحانات والواجبات.</value>
  </data>
  <data name="Permission_Messaging_ViewHistory" xml:space="preserve">
    <value>عرض سجل الرسائل</value>
  </data>
  <data name="PermissionDescription_Messaging_ViewHistory" xml:space="preserve">
    <value>بيسمح بعرض سجل الرسائل المرسلة.</value>
  </data>
  <data name="Permission_Messaging_SendManual" xml:space="preserve">
    <value>إرسال رسالة يدوية</value>
  </data>
  <data name="PermissionDescription_Messaging_SendManual" xml:space="preserve">
    <value>بيسمح بإرسال رسالة يدوية للطلاب أو أولياء الأمور.</value>
  </data>
  <data name="Permission_Messaging_ManageTemplates" xml:space="preserve">
    <value>إدارة قوالب الرسائل</value>
  </data>
  <data name="PermissionDescription_Messaging_ManageTemplates" xml:space="preserve">
    <value>بيسمح بإنشاء وتعديل قوالب الرسائل.</value>
  </data>
  <data name="Permission_Messaging_ConfigureAutomatedTriggers" xml:space="preserve">
    <value>إعداد الرسائل التلقائية</value>
  </data>
  <data name="PermissionDescription_Messaging_ConfigureAutomatedTriggers" xml:space="preserve">
    <value>بيسمح بإعداد شروط إرسال الرسائل التلقائية.</value>
  </data>
  <data name="Permission_Videos_View" xml:space="preserve">
    <value>عرض الفيديوهات</value>
  </data>
  <data name="PermissionDescription_Videos_View" xml:space="preserve">
    <value>بيسمح بعرض الفيديوهات المرفوعة.</value>
  </data>
  <data name="Permission_Videos_ManageVideos" xml:space="preserve">
    <value>إدارة الفيديوهات</value>
  </data>
  <data name="PermissionDescription_Videos_ManageVideos" xml:space="preserve">
    <value>بيسمح برفع الفيديوهات وتعديلها وحذفها.</value>
  </data>
  <data name="Permission_OnlineExam_View" xml:space="preserve">
    <value>عرض الامتحانات الأونلاين</value>
  </data>
  <data name="PermissionDescription_OnlineExam_View" xml:space="preserve">
    <value>بيسمح بعرض الامتحانات الأونلاين.</value>
  </data>
  <data name="Permission_OnlineExam_ManageExams" xml:space="preserve">
    <value>إدارة الامتحانات الأونلاين</value>
  </data>
  <data name="PermissionDescription_OnlineExam_ManageExams" xml:space="preserve">
    <value>بيسمح بإنشاء وتعديل وإدارة الامتحانات الأونلاين.</value>
  </data>
  <data name="Permission_Payment_ConfirmDeparture" xml:space="preserve">
    <value>تأكيد انسحاب الطالب واسترداد المبلغ</value>
  </data>
  <data name="PermissionDescription_Payment_ConfirmDeparture" xml:space="preserve">
    <value>بيسمح بتأكيد انسحاب الطالب من الكورس ومعالجة استرداد المبلغ أو تسوية المبلغ المستحق.</value>
  </data>
</root>
'@
Apply-Edit -Path $path24 -Old $edit24Old -New $edit24New -Description 'Messages.ar.resx - insert error-message keys + module/permission localization keys'

# -------------------------------------------------------------------------------------
# Edit 25 of 25  -  new file: PermissionLocalizationExtensions.cs
# -------------------------------------------------------------------------------------
$newFilePath = Join-Path $PSScriptRoot 'Edvanz.Application\Extensions\PermissionLocalizationExtensions.cs'
$newFileContent = @'
using System.Text;
using Edvanz.Domain.Resources;
using Microsoft.Extensions.Localization;

namespace Edvanz.Application.Extensions
{
    /// <summary>
    /// Resolves the localized display name/description for a Module or Permission at the
    /// presentation/response layer, per the current request's Accept-Language.
    ///
    /// Reuses the existing <see cref="IStringLocalizer{Messages}"/> mechanism — same resx files
    /// (Messages.en.resx / Messages.ar.resx), no parallel localization system. The underlying
    /// stable identifiers (<c>Module.Name</c>, <c>Permission.Name</c>, and the numeric
    /// <c>Permission.Id</c> everything actually matches on for authorization/writes) are never
    /// touched — this only affects what a DTO puts in its display-text fields.
    ///
    /// KEY CONVENTION:
    ///   Module_{ModuleKey}
    ///   Permission_{ModuleKey}_{PermissionKey}
    ///   PermissionDescription_{ModuleKey}_{PermissionKey}
    /// where {ModuleKey}/{PermissionKey} are the seeded Name with every non-alphanumeric
    /// character stripped (resx data names can't contain spaces/hyphens). E.g. module
    /// "Event-Based Payment" + permission "View" → key "Permission_EventBasedPayment_View".
    /// Permission names repeat across modules ("View", "Edit", ...), so the module qualifier is
    /// required to avoid collisions — do not shorten this key shape.
    ///
    /// FALLBACK: if a resx entry is missing for a given key (new module/permission added without
    /// a matching translation yet), the raw seeded Name / stored Description is returned instead
    /// of the key itself, so the API never leaks an unresolved resx key to a client.
    /// </summary>
    public static class PermissionLocalizationExtensions
    {
        private static string SanitizeKey(string name)
        {
            var builder = new StringBuilder(name.Length);
            foreach (char c in name)
            {
                if (char.IsLetterOrDigit(c))
                    builder.Append(c);
            }
            return builder.ToString();
        }

        /// <summary>Localized module display name, falling back to <paramref name="moduleName"/>.</summary>
        public static string GetLocalizedModuleName(this IStringLocalizer<Messages> localizer, string moduleName)
        {
            var localized = localizer[$"Module_{SanitizeKey(moduleName)}"];
            return localized.ResourceNotFound ? moduleName : localized.Value;
        }

        /// <summary>Localized permission display name, falling back to <paramref name="permissionName"/>.</summary>
        public static string GetLocalizedPermissionName(
            this IStringLocalizer<Messages> localizer, string moduleName, string permissionName)
        {
            var key = $"Permission_{SanitizeKey(moduleName)}_{SanitizeKey(permissionName)}";
            var localized = localizer[key];
            return localized.ResourceNotFound ? permissionName : localized.Value;
        }

        /// <summary>
        /// Localized permission description, falling back to <paramref name="storedDescription"/>
        /// (the raw <c>Permission.Description</c> column) and finally to null if neither exists.
        /// </summary>
        public static string? GetLocalizedPermissionDescription(
            this IStringLocalizer<Messages> localizer,
            string moduleName,
            string permissionName,
            string? storedDescription)
        {
            var key = $"PermissionDescription_{SanitizeKey(moduleName)}_{SanitizeKey(permissionName)}";
            var localized = localizer[key];
            return localized.ResourceNotFound ? storedDescription : localized.Value;
        }
    }
}

'@
New-FileWithContent -Path $newFilePath -Content $newFileContent -Description 'Create PermissionLocalizationExtensions.cs'

Write-Host ""
Write-Host "Done. Next steps:"
Write-Host "  1. Build the solution and check for errors."
Write-Host "  2. Run: dotnet ef migrations add AddPermissionDescriptionColumn --project Edvanz.Infrastructure --startup-project Edvanz.API"
Write-Host "  3. Run: dotnet ef migrations add SeedPermissionDescriptionsAndConfirmDeparturePermission --project Edvanz.Infrastructure --startup-project Edvanz.API"
Write-Host "     then paste the provided Up()/Down() body into that second (empty-scaffolded) migration."
Write-Host "  4. Grep the Angular/Flutter clients for any parsing of the old qualified Module.Permission string shape."