using Edvanz.Domain.Entities.ShareProp;
using Edvanz.Domain.Enums;
using System.ComponentModel.DataAnnotations.Schema;

namespace Edvanz.Domain.Entities;

/// <summary>
/// Append-only log of every Open and Stop event raised by Flutter for a video.
/// One row per event. Never updated, never deleted (except by the NoAction when
/// the parent video is hard-deleted).
///
/// PURPOSES:
/// <list type="number">
///   <item>
///     <b>Per-device anchor for delta validation (Story C).</b> When a Stop arrives
///     with <c>deltaSeconds</c>, the service finds the most recent prior event
///     for the same <c>(student, video, device)</c> tuple, computes the
///     server-elapsed time since that anchor's <see cref="EventUtc"/>, and
///     clamps the accepted delta to <c>elapsed + tolerance</c>. Without this
///     log, a tampering client could claim arbitrary watch time.
///   </item>
///   <item>
///     <b>Server-side idempotency (REQ-VCM-FR-03 idempotency design + Q4(b)).</b>
///     <see cref="ClientEventId"/> is a UUID generated by Flutter per Open or
///     Stop event and persisted on this row under a unique filtered index. A
///     network retry that re-sends the same event id observes the unique-
///     constraint violation, and the service returns the original result instead
///     of double-incrementing analytics.
///   </item>
///   <item>
///     <b>Future per-video timeline reports.</b> The append-only event stream is
///     a strict superset of the aggregate <see cref="VideoAnalytics"/> table.
///     Reports that need event-level granularity ("when in the day do students
///     watch?") read from here.
///   </item>
/// </list>
///
/// COMPOSITE TENANT SCOPE: <see cref="TeacherId"/> participates in the
/// <c>(VideoAssetId, TeacherId)</c> composite FK with the parent video. The
/// fluent API is the single source of truth — see <see cref="VideoScope"/> for
/// why <c>[ForeignKey(nameof(Teacher))]</c> is intentionally omitted.
/// </summary>
public class VideoWatchEvent : BaseEntity
{
    // ══════════════════════════════════════════════
    // VIDEO LINKAGE & TENANT SCOPE
    // ══════════════════════════════════════════════

    /// <summary>
    /// The video this event refers to. NoAction-deleted with the video via the
    /// composite FK in fluent API.
    /// </summary>
    public long VideoAssetId { get; set; }

    /// <summary>The owning video.</summary>
    public VideoAsset VideoAsset { get; set; } = null!;

    /// <summary>
    /// Foreign key to the owning Teacher (denormalized; composite-FK enforced).
    /// </summary>
    public long TeacherId { get; set; }

    /// <summary>The teacher (denormalized).</summary>
    public Teacher Teacher { get; set; } = null!;

    /// <summary>
    /// The student who raised the event. NoAction-deleted with the student.
    /// </summary>
    [ForeignKey(nameof(TeacherStudent))]
    public long TeacherStudentId { get; set; }

    /// <summary>The student.</summary>
    public TeacherStudent TeacherStudent { get; set; } = null!;

    // ══════════════════════════════════════════════
    // EVENT IDENTITY
    // ══════════════════════════════════════════════

    /// <summary>
    /// Stable per-install UUID generated by Flutter the first time the app runs
    /// on a given device, persisted on-device, and sent on every event from
    /// then on. Used <i>only</i> for partitioning per-device anchor lookups —
    /// never for authorization. A student watching on phone and tablet
    /// concurrently produces two distinct anchor chains because the
    /// <see cref="DeviceId"/> differs.
    /// </summary>
    public string DeviceId { get; set; } = null!;

    /// <summary>
    /// Whether this row records an Open or a Stop. Persisted as <c>tinyint</c>.
    /// </summary>
    public VideoEventType EventType { get; set; }

    // ══════════════════════════════════════════════
    // PLAYER STATE AT EVENT TIME
    // ══════════════════════════════════════════════

    /// <summary>
    /// The player's position in seconds at the moment of the event. For Open
    /// events, this is where the player will resume to (server-computed, equal
    /// to <c>VideoAnalytics.LastResumePositionSeconds</c> at the time of read).
    /// For Stop events, this is where the student stopped.
    /// </summary>
    public int PositionSeconds { get; set; }

    /// <summary>
    /// Always 0 for Open events. For Stop events: the server-validated, clamped
    /// delta in seconds — see <see cref="VideoAnalytics.TotalWatchSeconds"/>
    /// remarks for the two-layer clamping rules. This is the value that was
    /// actually added to the aggregate, not the raw client-supplied number.
    /// </summary>
    public int DeltaSinceLastSeconds { get; set; }

    // ══════════════════════════════════════════════
    // TIMING & IDEMPOTENCY
    // ══════════════════════════════════════════════

    /// <summary>
    /// Server-side UTC time at which the event row was inserted. ALWAYS set to
    /// <c>DateTime.UtcNow</c> in service code — never copied from the client
    /// payload. Client clocks are untrusted (REQ-VCM-NFR-04).
    /// </summary>
    public DateTime EventUtc { get; set; }

    /// <summary>
    /// Optional idempotency key supplied by Flutter. When present, a unique
    /// filtered index ensures the same event is recorded at most once across
    /// retries. When absent (e.g., older client builds), idempotency is not
    /// enforced for this event.
    /// <para>
    /// Spec §3.8 / Q4(b): covers both Open and Stop events.
    /// </para>
    /// </summary>
    public Guid? ClientEventId { get; set; }
}
