using System.Text.Json.Serialization;

namespace Edvanz.Domain.Enums;

/// <summary>
/// The lifecycle status of an assignment occurrence (a single instance of a template,
/// for example one specific weekly homework due on a specific date).
///
/// NAMING NOTE: This enum is distinct from <see cref="OccurrenceStatus"/> in the
/// Attendance module. They serve different domains:
///   - <see cref="OccurrenceStatus"/> tracks attendance-marking progress for a session.
///   - <see cref="AssignmentOccurrenceStatus"/> tracks the lifecycle of an assignment instance.
///
/// Stored as tinyint in the database.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum AssignmentOccurrenceStatus : byte
{
    /// <summary>
    /// The occurrence has been generated by the scheduler but its due date has not yet arrived.
    /// All student obligations under this occurrence are also Pending.
    /// REQ-EXH-007: Pending state at the moment of creation.
    /// </summary>
    Pending = 0,

    /// <summary>
    /// The occurrence is currently open for grade entry and status updates.
    /// At least one student obligation has been recorded.
    /// </summary>
    Active = 1,

    /// <summary>
    /// The occurrence is closed — no further status or grade entries are expected.
    /// Used for reporting filters and to gate edit operations.
    /// </summary>
    Completed = 2
}
