namespace Edvanz.Domain.Enums;

/// <summary>
/// Determines whether a value (student code, session name) is auto-generated by the system or manually entered by the teacher.
/// Used by AAM-FR-04.2 (Student Code Generation) and AAM-FR-04.3 (Session Name Configuration).
/// </summary>
public enum GenerationMode
{
    Auto = 1,
    Manual = 2
}